LSAY analysis
grattan/school-ed-2025-primary-maths pull request #1
Opened 2024-07-03 06:45 UTC by tsat0002

initial analysis of LSAY data - 2003

2024-07-07 10:50 UTC, nickjparkinson commented
Hi Tash! I've had a quick look and don't have any substantial feedback yet. I'll dive in a little deeper later this week. Great work in your first six days. Super pleased with how much progress you've made.

2024-07-07 10:51 UTC, nickjparkinson commented
Keep working on your branch for now and I'll review the PR and merge once ready.

2024-07-10 07:02 UTC, tsat0002 commented
I was able to figure out what was going on with the data frame - the strings in `Benchmark` were formatted slightly different, it works now.
 [c4b8585](https://github.com/grattan/school-ed-2025-primary-maths/pull/1/commits/c4b8585049fcaeef5b701499814d61c663431a66) has the tables for the averages across the years and honestly I think `intsvy` does a bit better of a job than the `survey` package (clear reduction across the states over 03, 06, 09).

2024-07-12 05:14 UTC, nickjparkinson requested changes
Hi Tash!

This code is brilliant. I'm so impressed with how far you've got. As a next step, please see my changed and incorporate my upstream pull request. 

I'd then recommend going back over each cohort, and adapting my code which uses the Rrepest package.

2024-07-12 05:14 UTC, nickjparkinson commented on LSAY_EDA.qmd
> +Seems as though the level 3 proficiency levels for mathematics literacy is 482 in later years as well. \* [2018](https://nces.ed.gov/surveys/pisa/pisa2018/pdf/MathProfLevelDescriptionV2.pdf) \* [2022
See my changes upstream, where I estimate the mean and standard deviation using the Rrepest package. This method is simpler and the most accurate method. The result is very close to your estimates using intsvy. The difference is explainable by the fact that I've weighted each replicate, whereas you've used a final weight.

2024-07-12 05:14 UTC, nickjparkinson commented on LSAY_EDA.qmd
> +library(survey)
See my code for how I've figured out the percentage who are not proficient. Note the large standard error on my estimates. This is important when working with a small sample. I get a very similar result (13 per cent), but it's using a slightly more robust method.

2024-09-23 23:39 UTC, merged